pub mod aggregate;

// Generated by build.rs from metadata.json
// Contains ENTITY_METADATA and FIELDS constants
#[allow(dead_code)]
mod metadata_gen;

// Re-export for external access
pub use metadata_gen::{ENTITY_METADATA, FIELDS};