//! LLM Artifact Domain Module
//!
//! Артефакты, создаваемые LLM агентами в процессе работы с чатами.
//! Включает SQL запросы, параметры, конфигурации визуализации.

pub mod aggregate;

// Generated by build.rs from metadata.json
#[allow(dead_code)]
mod metadata_gen;
pub use metadata_gen::{ENTITY_METADATA, FIELDS};

pub use aggregate::{
    ArtifactStatus, ArtifactType, LlmArtifact, LlmArtifactId, LlmArtifactListItem,
};
