#![allow(deprecated)]

use contracts::shared::universal_dashboard::{DataSourceSchema, FieldDef, FieldType};

/// DS03 Sales Data schema (p904_sales_data)
pub static DS03_SCHEMA: DataSourceSchema = DataSourceSchema {
    id: "ds03_p904_sales",
    name: "Данные продаж",
    fields: &[
        // Dimension fields (can_filter = true)
        FieldDef {
            id: "date",
            name: "Дата",
            field_type: FieldType::Date,
            can_group: true,
            can_aggregate: false,
            can_filter: true,
            db_column: "date",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "article",
            name: "Артикул продавца",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            can_filter: true,
            db_column: "article",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "registrator_type",
            name: "Тип регистратора",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            can_filter: true,
            db_column: "registrator_type",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "connection_mp_ref",
            name: "Кабинет МП",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            can_filter: true,
            db_column: "connection_mp_ref",
            ref_table: Some("a006_connection_mp"),
            ref_display_column: Some("description"),
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "nomenclature_ref",
            name: "Номенклатура",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            can_filter: true,
            db_column: "nomenclature_ref",
            ref_table: Some("a004_nomenclature"),
            ref_display_column: Some("description"),
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "marketplace",
            name: "Маркетплейс",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            can_filter: true,
            db_column: "marketplace",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a006_connection_mp"),
            join_on_column: Some("connection_mp_ref"),
        },
        FieldDef {
            id: "dim1",
            name: "Измерение 1 (категория)",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            can_filter: false,
            db_column: "dim1_category",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        FieldDef {
            id: "dim2",
            name: "Измерение 2 (линейка)",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            can_filter: false,
            db_column: "dim2_line",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        FieldDef {
            id: "dim3",
            name: "Измерение 3 (модель)",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            can_filter: false,
            db_column: "dim3_model",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        FieldDef {
            id: "dim4",
            name: "Измерение 4 (формат)",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            can_filter: false,
            db_column: "dim4_format",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        FieldDef {
            id: "dim5",
            name: "Измерение 5 (назначение)",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            can_filter: false,
            db_column: "dim5_sink",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        FieldDef {
            id: "dim6",
            name: "Измерение 6 (размер)",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            can_filter: false,
            db_column: "dim6_size",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        // Metric fields (can_filter = false)
        FieldDef {
            id: "customer_in",
            name: "Сумма выручка",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            can_filter: false,
            db_column: "customer_in",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "customer_out",
            name: "Сумма возвраты",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            can_filter: false,
            db_column: "customer_out",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "seller_out",
            name: "Сумма продавцу",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            can_filter: false,
            db_column: "seller_out",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "commission_out",
            name: "Сумма комиссия",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            can_filter: false,
            db_column: "commission_out",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "logistics_out",
            name: "Сумма логистика",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            can_filter: false,
            db_column: "logistics_out",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "cost",
            name: "Сумма себестоимость",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            can_filter: false,
            db_column: "cost",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "order_count",
            name: "Кол-во заказов",
            field_type: FieldType::Integer,
            can_group: false,
            can_aggregate: true,
            can_filter: false,
            db_column: "registrator_ref",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
    ],
    schema_filters: &[
        "date",
        "connection_mp_ref",
        "marketplace",
        "registrator_type",
    ],
};

/// Main table name for DS03
pub const DS03_TABLE_NAME: &str = "p904_sales_data";
