// ============================================================================
// AUTO-GENERATED FROM metadata.json - DO NOT EDIT MANUALLY
// ============================================================================

#![allow(dead_code)]

use crate::shared::metadata::{
    EntityMetadataInfo, EntityType, EntityUiMetadata, EntityAiMetadata,
    FieldMetadata, FieldType, FieldSource, FieldUiMetadata, ValidationRules
};
use crate::shared::access::{EntityAccessMeta, ScopeOperation, AccessMode};

/// Access scope metadata for this entity
pub const ACCESS_META: EntityAccessMeta = EntityAccessMeta {
    scope_id: "a038_llm_connection",
    operations: &[
    ScopeOperation { id: "list", required_mode: AccessMode::Read },
    ScopeOperation { id: "get", required_mode: AccessMode::Read },
    ScopeOperation { id: "upsert", required_mode: AccessMode::All },
    ScopeOperation { id: "delete", required_mode: AccessMode::All }
    ],
};

/// Entity metadata for LlmConnection aggregate
pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Aggregate,
    entity_name: "LlmConnection",
    entity_index: "a038",
    collection_name: "llm_connection",
    table_name: Some("a038_llm_connection"),
    ui: EntityUiMetadata {
        element_name: "Подключение LLM",
        element_name_en: Some("LLM Connection"),
        list_name: "Подключения LLM",
        list_name_en: Some("LLM Connections"),
        icon: Some("plug-connected"),
    },
    ai: EntityAiMetadata {
        description: "Подключение к провайдеру LLM (OpenAI, OpenRouter). Содержит API-ключ, эндпоинт, параметры модели (temperature, max_tokens), системный промпт и курируемый список разрешённых моделей (allowed_models). Чат работает через одно подключение и переключает модель в пределах allowed_models.",
        questions: &["Какие LLM подключения настроены?", "Как добавить подключение OpenRouter?", "Какие модели разрешены для подключения?", "Как изменить список моделей подключения?"],
        related: &["a018_llm_chat", "a019_llm_artifact"],
    },
    access: Some(&ACCESS_META),
};

/// Field metadata array
pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "LlmConnectionId",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID",
            label_en: Some("ID"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "code",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Код",
            label_en: Some("Code"),
            placeholder: Some("OPENROUTER-MAIN"),
            hint: Some("Уникальный код подключения"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(50),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "description",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Наименование",
            label_en: Some("Name"),
            placeholder: Some("OpenRouter основное подключение"),
            hint: Some("Описательное название подключения"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(250),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: Some(3),
            max_length: Some(255),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "comment",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Комментарий",
            label_en: Some("Comment"),
            placeholder: Some("Используется для аналитики продаж"),
            hint: Some("Произвольный комментарий"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(1000),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "provider_type",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Провайдер",
            label_en: Some("Provider"),
            placeholder: None,
            hint: Some("Тип провайдера LLM"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("select"),
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Реально поддерживаемые провайдеры: OpenAI (GPT), OpenRouter (кросс-вендорный OpenAI-совместимый роутинг)"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "api_endpoint",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "API Endpoint",
            label_en: Some("API Endpoint"),
            placeholder: Some("https://openrouter.ai/api/v1"),
            hint: Some("URL эндпоинта API провайдера"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: Some(300),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(500),
            pattern: Some("^https?://.+"),
            custom_error: Some("URL должен начинаться с http:// или https://"),
        },
        ai_hint: Some("OpenAI: https://api.openai.com/v1, OpenRouter: https://openrouter.ai/api/v1"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "api_key",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "API Ключ",
            label_en: Some("API Key"),
            placeholder: Some("sk-..."),
            hint: Some("API ключ для аутентификации"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("password"),
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(500),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Хранится в зашифрованном виде."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "model_name",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Модель по умолчанию",
            label_en: Some("Default Model"),
            placeholder: Some("openai/gpt-4o"),
            hint: Some("Модель по умолчанию для новых чатов"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(100),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Должна входить в allowed_models. OpenAI: gpt-4o. OpenRouter: openai/gpt-4o, anthropic/claude-sonnet-5, deepseek/deepseek-chat"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "available_models",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Доступные модели",
            label_en: Some("Available Models"),
            placeholder: None,
            hint: Some("JSON список моделей из API (кэш fetch-models)"),
            visible_in_list: false,
            visible_in_form: false,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON массив объектов с полями id, created, owned_by. Загружается из /v1/models API провайдера."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "allowed_models",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Разрешённые модели",
            label_en: Some("Allowed Models"),
            placeholder: None,
            hint: Some("Курируемый короткий список моделей (JSON-массив id)"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON массив model_id — подмножество available_models. Только эти модели можно выбрать в чате. Держите 3-8 технически совместимых и целесообразных моделей."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "temperature",
        rust_type: "f64",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Temperature",
            label_en: Some("Temperature"),
            placeholder: Some("0.7"),
            hint: Some("Креативность ответов (0.0-2.0)"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: Some(0.0),
            max: Some(2.0),
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("0.0 - детерминированно, 1.0 - сбалансированно, 2.0 - максимально креативно"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "max_tokens",
        rust_type: "i32",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Max Tokens",
            label_en: Some("Max Tokens"),
            placeholder: Some("4096"),
            hint: Some("Максимальная длина ответа"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: Some(256.0),
            max: Some(128000.0),
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("GPT-4o поддерживает до 128k токенов"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "system_prompt",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Системный промпт",
            label_en: Some("System Prompt"),
            placeholder: Some("Ты аналитик данных маркетплейсов..."),
            hint: Some("Базовая инструкция (персона)"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(5000),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Определяет роль и поведение. Если пусто — используется role-agnostic core-промпт из skills."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "is_primary",
        rust_type: "bool",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Основное",
            label_en: Some("Primary"),
            placeholder: None,
            hint: Some("Использовать по умолчанию"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("checkbox"),
            column_width: Some(100),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Только одно подключение может быть основным. При установке флага автоматически снимается с других."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
