-- Ready-to-use BI indicators for dv003_mp_order_line_turnovers.

INSERT OR IGNORE INTO a024_bi_indicator (
    id,
    code,
    description,
    comment,
    data_spec_json,
    params_json,
    view_spec_json,
    drill_spec_json,
    status,
    owner_user_id,
    is_public,
    created_by,
    updated_by,
    is_deleted,
    is_posted,
    created_at,
    updated_at,
    version
) VALUES
(
    'a024a024-0009-4001-a001-000000000009',
    'IND-MP-REV-PRICE',
    'Выручка (прайс) MP',
    'Готовый BI-индикатор на DataView dv003_mp_order_line_turnovers, metric=revenue_price',
    '{"view_id":"dv003_mp_order_line_turnovers","metric_id":"revenue_price"}',
    '[]',
    '{"style_name":"classic","custom_html":null,"custom_css":null,"format":{"kind":"Money","currency":"RUB"},"thresholds":[],"preview_values":{}}',
    NULL,
    'active',
    'f2fc6986-855d-492b-acff-70c7cd8cdd34',
    1,
    'system',
    'system',
    0,
    1,
    datetime('now'),
    datetime('now'),
    1
),
(
    'a024a024-0010-4001-a001-000000000010',
    'IND-MP-REV',
    'Выручка MP',
    'Готовый BI-индикатор на DataView dv003_mp_order_line_turnovers, metric=revenue',
    '{"view_id":"dv003_mp_order_line_turnovers","metric_id":"revenue"}',
    '[]',
    '{"style_name":"classic","custom_html":null,"custom_css":null,"format":{"kind":"Money","currency":"RUB"},"thresholds":[],"preview_values":{}}',
    NULL,
    'active',
    'f2fc6986-855d-492b-acff-70c7cd8cdd34',
    1,
    'system',
    'system',
    0,
    1,
    datetime('now'),
    datetime('now'),
    1
),
(
    'a024a024-0011-4001-a001-000000000011',
    'IND-MP-COINVEST',
    'Соинвест MP',
    'Готовый BI-индикатор на DataView dv003_mp_order_line_turnovers, metric=coinvest',
    '{"view_id":"dv003_mp_order_line_turnovers","metric_id":"coinvest"}',
    '[]',
    '{"style_name":"classic","custom_html":null,"custom_css":null,"format":{"kind":"Money","currency":"RUB"},"thresholds":[],"preview_values":{}}',
    NULL,
    'active',
    'f2fc6986-855d-492b-acff-70c7cd8cdd34',
    1,
    'system',
    'system',
    0,
    1,
    datetime('now'),
    datetime('now'),
    1
),
(
    'a024a024-0012-4001-a001-000000000012',
    'IND-MP-ACQUIRING',
    'Эквайринг MP',
    'Готовый BI-индикатор на DataView dv003_mp_order_line_turnovers, metric=acquiring',
    '{"view_id":"dv003_mp_order_line_turnovers","metric_id":"acquiring"}',
    '[]',
    '{"style_name":"classic","custom_html":null,"custom_css":null,"format":{"kind":"Money","currency":"RUB"},"thresholds":[],"preview_values":{}}',
    NULL,
    'active',
    'f2fc6986-855d-492b-acff-70c7cd8cdd34',
    1,
    'system',
    'system',
    0,
    1,
    datetime('now'),
    datetime('now'),
    1
),
(
    'a024a024-0013-4001-a001-000000000013',
    'IND-MP-COST',
    'Себестоимость MP',
    'Готовый BI-индикатор на DataView dv003_mp_order_line_turnovers, metric=cost',
    '{"view_id":"dv003_mp_order_line_turnovers","metric_id":"cost"}',
    '[]',
    '{"style_name":"classic","custom_html":null,"custom_css":null,"format":{"kind":"Money","currency":"RUB"},"thresholds":[],"preview_values":{}}',
    NULL,
    'active',
    'f2fc6986-855d-492b-acff-70c7cd8cdd34',
    1,
    'system',
    'system',
    0,
    1,
    datetime('now'),
    datetime('now'),
    1
),
(
    'a024a024-0014-4001-a001-000000000014',
    'IND-MP-COMMISSION',
    'Комиссия MP',
    'Готовый BI-индикатор на DataView dv003_mp_order_line_turnovers, metric=commission',
    '{"view_id":"dv003_mp_order_line_turnovers","metric_id":"commission"}',
    '[]',
    '{"style_name":"classic","custom_html":null,"custom_css":null,"format":{"kind":"Money","currency":"RUB"},"thresholds":[],"preview_values":{}}',
    NULL,
    'active',
    'f2fc6986-855d-492b-acff-70c7cd8cdd34',
    1,
    'system',
    'system',
    0,
    1,
    datetime('now'),
    datetime('now'),
    1
),
(
    'a024a024-0015-4001-a001-000000000015',
    'IND-MP-RETURNS',
    'Возвраты MP',
    'Готовый BI-индикатор на DataView dv003_mp_order_line_turnovers, metric=returns',
    '{"view_id":"dv003_mp_order_line_turnovers","metric_id":"returns"}',
    '[]',
    '{"style_name":"classic","custom_html":null,"custom_css":null,"format":{"kind":"Money","currency":"RUB"},"thresholds":[],"preview_values":{}}',
    NULL,
    'active',
    'f2fc6986-855d-492b-acff-70c7cd8cdd34',
    1,
    'system',
    'system',
    0,
    1,
    datetime('now'),
    datetime('now'),
    1
);
