-- Ready-to-use percentage BI indicators on top of dv006_indicator_ratio_percent.

INSERT OR IGNORE INTO a024_bi_indicator (
    id,
    code,
    description,
    comment,
    data_spec_json,
    params_json,
    view_spec_json,
    drill_spec_json,
    status,
    owner_user_id,
    is_public,
    created_by,
    updated_by,
    is_deleted,
    is_posted,
    created_at,
    updated_at,
    version
) VALUES
(
    'a024a024-0020-4001-a001-000000000020',
    'IND-REV-TO-PRICE-PCT',
    'Выручка к прайсу, %',
    'Ready-to-use BI indicator on DataView dv006_indicator_ratio_percent with numerator=REVENUE and denominator=IND-MP-REV-PRICE.',
    '{"view_id":"dv006_indicator_ratio_percent","metric_id":"ratio_percent"}',
    '[{"key":"numerator_indicator_code","param_type":"string","label":"Numerator indicator code","default_value":"REVENUE","required":true,"global_filter_key":null},{"key":"denominator_indicator_code","param_type":"string","label":"Denominator indicator code","default_value":"IND-MP-REV-PRICE","required":true,"global_filter_key":null}]',
    '{"style_name":"classic","custom_html":null,"custom_css":null,"format":{"kind":"Percent","decimals":1},"thresholds":[],"preview_values":{}}',
    NULL,
    'active',
    'f2fc6986-855d-492b-acff-70c7cd8cdd34',
    1,
    'system',
    'system',
    0,
    1,
    datetime('now'),
    datetime('now'),
    1
),
(
    'a024a024-0021-4001-a001-000000000021',
    'IND-GL-7609-TO-PRICE-PCT',
    '7609 к прайсу, %',
    'Ready-to-use BI indicator on DataView dv006_indicator_ratio_percent with numerator=IND-GL-7609-MAIN-BALANCE and denominator=IND-MP-REV-PRICE.',
    '{"view_id":"dv006_indicator_ratio_percent","metric_id":"ratio_percent"}',
    '[{"key":"numerator_indicator_code","param_type":"string","label":"Numerator indicator code","default_value":"IND-GL-7609-MAIN-BALANCE","required":true,"global_filter_key":null},{"key":"denominator_indicator_code","param_type":"string","label":"Denominator indicator code","default_value":"IND-MP-REV-PRICE","required":true,"global_filter_key":null}]',
    '{"style_name":"classic","custom_html":null,"custom_css":null,"format":{"kind":"Percent","decimals":1},"thresholds":[],"preview_values":{}}',
    NULL,
    'active',
    'f2fc6986-855d-492b-acff-70c7cd8cdd34',
    1,
    'system',
    'system',
    0,
    1,
    datetime('now'),
    datetime('now'),
    1
);
