-- Ready-to-use BI indicators for return count and return/revenue ratio.

INSERT OR IGNORE INTO a024_bi_indicator (
    id,
    code,
    description,
    comment,
    data_spec_json,
    params_json,
    view_spec_json,
    drill_spec_json,
    status,
    owner_user_id,
    is_public,
    created_by,
    updated_by,
    is_deleted,
    is_posted,
    created_at,
    updated_at,
    version
) VALUES
(
    'a024a024-0022-4001-a001-000000000022',
    'IND-MP-RETURNS-COUNT',
    'Количество возвратов',
    'Ready-to-use BI indicator on DataView dv004_general_ledger_turnovers with metric=entry_count, turnover_code=customer_revenue_pl_storno and layer=oper.',
    '{"view_id":"dv004_general_ledger_turnovers","metric_id":"entry_count"}',
    '[{"key":"turnover_code","param_type":"string","label":"Turnover code","default_value":"customer_revenue_pl_storno","required":true,"global_filter_key":null},{"key":"layer","param_type":"string","label":"Layer","default_value":"oper","required":true,"global_filter_key":null}]',
    '{"style_name":"classic","custom_html":null,"custom_css":null,"format":{"kind":"Integer"},"thresholds":[],"preview_values":{}}',
    NULL,
    'active',
    'f2fc6986-855d-492b-acff-70c7cd8cdd34',
    1,
    'system',
    'system',
    0,
    1,
    datetime('now'),
    datetime('now'),
    1
),
(
    'a024a024-0023-4001-a001-000000000023',
    'IND-MP-RETURNS-TO-REV-PCT',
    'Возвраты к реализации, %',
    'Ready-to-use BI indicator on DataView dv007_gl_turnover_ratio_percent with numerator=customer_revenue_pl_storno/oper and denominator=customer_revenue_pl/oper.',
    '{"view_id":"dv007_gl_turnover_ratio_percent","metric_id":"ratio_percent"}',
    '[{"key":"numerator_turnover_code","param_type":"string","label":"Numerator turnover code","default_value":"customer_revenue_pl_storno","required":true,"global_filter_key":null},{"key":"numerator_layer","param_type":"string","label":"Numerator layer","default_value":"oper","required":true,"global_filter_key":null},{"key":"denominator_turnover_code","param_type":"string","label":"Denominator turnover code","default_value":"customer_revenue_pl","required":true,"global_filter_key":null},{"key":"denominator_layer","param_type":"string","label":"Denominator layer","default_value":"oper","required":true,"global_filter_key":null}]',
    '{"style_name":"classic","custom_html":null,"custom_css":null,"format":{"kind":"Percent","decimals":1},"thresholds":[],"preview_values":{}}',
    NULL,
    'active',
    'f2fc6986-855d-492b-acff-70c7cd8cdd34',
    1,
    'system',
    'system',
    0,
    1,
    datetime('now'),
    datetime('now'),
    1
);
