#![allow(dead_code)]

use crate::shared::metadata::{
    EntityAiMetadata, EntityMetadataInfo, EntityType, EntityUiMetadata, FieldMetadata, FieldSource,
    FieldType, FieldUiMetadata, ValidationRules,
};

pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Projection,
    entity_name: "MpFinanceTurnover",
    entity_index: "p914",
    collection_name: "mp_finance_turnovers",
    table_name: Some("p914_mp_finance_turnovers"),
    ui: EntityUiMetadata {
        element_name: "MP Finance Turnovers",
        element_name_en: Some("MP Finance Turnovers"),
        list_name: "MP Finance Turnovers",
        list_name_en: Some("MP Finance Turnovers"),
        icon: Some("database"),
    },
    ai: EntityAiMetadata {
        description: "Проекция финансовых оборотов слоя fina. Одна запись = одна GL-проводка слоя fina, построенная из финансового отчёта МП (p903/p907). Совпадает с GL по сумме, дате транзакции, turnover_code и основным измерениям; добавляет разрезы customer_kind и fulfillment_type для отчётности.",
        questions: &[
            "Какие финансовые обороты слоя fina есть за период?",
            "Какой turnover_code даёт выручку, комиссию, эквайринг или сторно возврата?",
            "Какие обороты приходятся на юрлиц (UL) и физлиц (FL)?",
            "Какие обороты по схеме FBO, FBS или FBW?",
        ],
        related: &[
            "p903_wb_finance_report",
            "p907_ym_payment_report",
            "general_ledger",
        ],
    },
    access: None,
};

pub const FIELDS: &[FieldMetadata] = &[
    field(
        "id",
        "String",
        "ID",
        true,
        true,
        Some("Стабильный business key строки проекции (= general_ledger_ref)."),
        None,
        None,
    ),
    field(
        "transaction_date",
        "String",
        "Transaction Date",
        true,
        true,
        Some("Дата транзакции (совпадает с entry_date GL-проводки)."),
        None,
        None,
    ),
    field(
        "general_ledger_ref",
        "Option<String>",
        "General Ledger Ref",
        false,
        false,
        Some("Ссылка на зеркалируемую GL-проводку слоя fina."),
        None,
        None,
    ),
    field(
        "registrator_type",
        "String",
        "Registrator Type",
        true,
        true,
        Some("Тип документа-источника: p903_wb_finance_report или p907_ym_payment_report."),
        None,
        None,
    ),
    field(
        "registrator_ref",
        "String",
        "Registrator Ref",
        true,
        true,
        Some("Ссылка на конкретную строку источника."),
        None,
        None,
    ),
    field(
        "connection_mp_ref",
        "String",
        "Connection",
        true,
        true,
        Some("UUID кабинета маркетплейса."),
        Some("a006_connection_mp"),
        None,
    ),
    field(
        "nomenclature_ref",
        "Option<String>",
        "Nomenclature",
        false,
        false,
        Some("Ссылка на a004_nomenclature."),
        Some("a004_nomenclature"),
        None,
    ),
    field(
        "marketplace_product_ref",
        "Option<String>",
        "Marketplace Product",
        false,
        false,
        Some("Ссылка на a007_marketplace_product."),
        Some("a007_marketplace_product"),
        None,
    ),
    field(
        "turnover_code",
        "String",
        "Turnover Code",
        true,
        true,
        Some("Код оборота из классификатора turnover classes."),
        None,
        None,
    ),
    field(
        "order_key",
        "String",
        "Order Key",
        true,
        true,
        Some("Бизнес-ключ заказа (srid для WB, order_id для YM)."),
        None,
        None,
    ),
    field(
        "order_ref",
        "Option<String>",
        "Order Ref",
        false,
        false,
        Some("UUID агрегата-заказа (a015_wb_orders / a013_ym_order), если есть."),
        None,
        None,
    ),
    field(
        "order_registrator_type",
        "Option<String>",
        "Order Registrator Type",
        false,
        false,
        Some("Тип документа-заказа: a015_wb_orders / a013_ym_order."),
        None,
        None,
    ),
    field(
        "event_kind",
        "String",
        "Event Kind",
        true,
        true,
        Some("Тип события: ordered, sold, returned, fee, adjustment, other."),
        None,
        Some(&["ordered", "sold", "returned", "fee", "adjustment", "other"]),
    ),
    field(
        "customer_kind",
        "Option<String>",
        "Customer Kind",
        true,
        false,
        Some("Тип покупателя: URL — юрлицо, FIZ — физлицо."),
        None,
        Some(&["URL", "FIZ"]),
    ),
    field(
        "fulfillment_type",
        "Option<String>",
        "Fulfillment Type",
        true,
        false,
        Some("Схема исполнения: FBO, FBS, FBW."),
        None,
        Some(&["FBO", "FBS", "FBW"]),
    ),
    field(
        "layer",
        "String",
        "Layer",
        true,
        true,
        Some("Слой оборота. Для этой проекции всегда fina."),
        None,
        Some(&["fina"]),
    ),
    field(
        "amount",
        "f64",
        "Amount",
        true,
        true,
        Some("Сумма оборота, совпадает с суммой GL-проводки."),
        None,
        None,
    ),
    field(
        "quantity",
        "Option<f64>",
        "Quantity",
        true,
        false,
        Some("Количество, если применимо к обороту."),
        None,
        None,
    ),
    field(
        "created_at_msk",
        "String",
        "Created At (MSK)",
        false,
        false,
        Some("Время создания строки проекции (MSK)."),
        None,
        None,
    ),
    field(
        "updated_at_msk",
        "String",
        "Updated At (MSK)",
        false,
        false,
        Some("Время последнего обновления строки проекции (MSK)."),
        None,
        None,
    ),
];

const fn field(
    name: &'static str,
    rust_type: &'static str,
    label: &'static str,
    visible_in_list: bool,
    required: bool,
    ai_hint: Option<&'static str>,
    ref_aggregate: Option<&'static str>,
    enum_values: Option<&'static [&'static str]>,
) -> FieldMetadata {
    FieldMetadata {
        name,
        rust_type,
        field_type: if ref_aggregate.is_some() {
            FieldType::AggregateRef
        } else if enum_values.is_some() {
            FieldType::Enum
        } else {
            FieldType::Primitive
        },
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label,
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint,
        nested_fields: None,
        ref_aggregate,
        enum_values,
    }
}
