#![allow(dead_code)]

use crate::shared::metadata::{
    EntityAiMetadata, EntityMetadataInfo, EntityType, EntityUiMetadata, FieldMetadata, FieldSource,
    FieldType, FieldUiMetadata, ValidationRules,
};

pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Projection,
    entity_name: "MpUnlinkedTurnover",
    entity_index: "p910",
    collection_name: "mp_unlinked_turnovers",
    table_name: Some("p910_mp_unlinked_turnovers"),
    ui: EntityUiMetadata {
        element_name: "MP Unlinked Turnovers",
        element_name_en: Some("MP Unlinked Turnovers"),
        list_name: "MP Unlinked Turnovers",
        list_name_en: Some("MP Unlinked Turnovers"),
        icon: Some("database"),
    },
    ai: EntityAiMetadata {
        description: "Универсальная проекция отвязанных оборотов маркетплейсов. Каждая строка хранит один turnover_code в одном layer с единым документом-источником.",
        questions: &[
            "Какие отвязанные расходы есть за период?",
            "Сколько storage, penalty или advertising пришло без связи со строкой заказа?",
            "Какие fact-строки из p903 ушли в p910, а не в p909?",
        ],
        related: &[
            "p903_wb_finance_report",
            "p909_mp_order_line_turnovers",
            "a006_connection_mp",
        ],
    },
    access: None,
};

pub const FIELDS: &[FieldMetadata] = &[
    field(
        "id",
        "String",
        "ID",
        true,
        true,
        Some("Стабильный business key строки отвязанного оборота."),
        None,
        None,
    ),
    field(
        "connection_mp_ref",
        "String",
        "Connection",
        true,
        true,
        Some("UUID кабинета маркетплейса."),
        Some("a006_connection_mp"),
        None,
    ),
    field(
        "entry_date",
        "String",
        "Entry Date",
        true,
        true,
        Some("Бизнес-дата отвязанного оборота."),
        None,
        None,
    ),
    field(
        "layer",
        "String",
        "Layer",
        true,
        true,
        Some("Слой оборота: plan, oper или fact."),
        None,
        Some(&["plan", "oper", "fact"]),
    ),
    field(
        "turnover_code",
        "String",
        "Turnover Code",
        true,
        true,
        Some("Код оборота из классификатора turnover classes."),
        None,
        None,
    ),
    field(
        "value_kind",
        "String",
        "Value Kind",
        true,
        true,
        Some("Тип значения: money, quantity, percent, coefficient."),
        None,
        Some(&["money", "quantity", "percent", "coefficient"]),
    ),
    field(
        "agg_kind",
        "String",
        "Aggregation Kind",
        false,
        true,
        Some("Правило агрегации для BI."),
        None,
        Some(&["sum", "avg", "last", "none"]),
    ),
    field(
        "amount",
        "f64",
        "Amount",
        true,
        true,
        Some("Значение отвязанного оборота в конкретном layer."),
        None,
        None,
    ),
    field(
        "registrator_type",
        "String",
        "Registrator Type",
        true,
        true,
        Some("Тип документа-источника, например p903_wb_finance_report."),
        None,
        None,
    ),
    field(
        "registrator_ref",
        "String",
        "Registrator Ref",
        true,
        true,
        Some("Ссылка на конкретный документ-источник."),
        None,
        None,
    ),
    field(
        "nomenclature_ref",
        "Option<String>",
        "Nomenclature",
        false,
        false,
        Some("Опциональная ссылка на a004_nomenclature."),
        Some("a004_nomenclature"),
        None,
    ),
    field(
        "comment",
        "Option<String>",
        "Comment",
        true,
        false,
        Some("Техническое пояснение или сырой label источника."),
        None,
        None,
    ),
    field(
        "created_at",
        "String",
        "Created At",
        false,
        false,
        Some("UTC timestamp создания строки проекции."),
        None,
        None,
    ),
    field(
        "updated_at",
        "String",
        "Updated At",
        false,
        false,
        Some("UTC timestamp последнего обновления строки проекции."),
        None,
        None,
    ),
];

const fn field(
    name: &'static str,
    rust_type: &'static str,
    label: &'static str,
    visible_in_list: bool,
    required: bool,
    ai_hint: Option<&'static str>,
    ref_aggregate: Option<&'static str>,
    enum_values: Option<&'static [&'static str]>,
) -> FieldMetadata {
    FieldMetadata {
        name,
        rust_type,
        field_type: if ref_aggregate.is_some() {
            FieldType::AggregateRef
        } else if enum_values.is_some() {
            FieldType::Enum
        } else {
            FieldType::Primitive
        },
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label,
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint,
        nested_fields: None,
        ref_aggregate,
        enum_values,
    }
}
