pub mod p900_mp_sales_register;
pub mod p901_nomenclature_barcodes;
pub mod p902_ozon_finance_realization;
pub mod p903_wb_finance_report;
pub mod p904_sales_data;
pub mod p905_wb_commission_history;
pub mod p906_nomenclature_prices;
pub mod p907_ym_payment_report;
pub mod p908_wb_goods_prices;