// ============================================================================
// AUTO-GENERATED FROM metadata.json - DO NOT EDIT MANUALLY
// Generated: 2026-02-24T13:55:25Z
// ============================================================================

#![allow(dead_code)]

use crate::shared::metadata::{
    EntityMetadataInfo, EntityType, EntityUiMetadata, EntityAiMetadata,
    FieldMetadata, FieldType, FieldSource, FieldUiMetadata, ValidationRules
};

/// Entity metadata for YmOrder aggregate
pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Aggregate,
    entity_name: "YmOrder",
    entity_index: "a013",
    collection_name: "ym_order",
    table_name: Some("a013_ym_order"),
    ui: EntityUiMetadata {
        element_name: "Заказ Яндекс.Маркет",
        element_name_en: Some("Yandex Market Order"),
        list_name: "Заказы Яндекс.Маркет",
        list_name_en: Some("Yandex Market Orders"),
        icon: Some("shopping-cart"),
    },
    ai: EntityAiMetadata {
        description: "Заказы с Яндекс.Маркет (YM). Каждая запись — один заказ, может содержать несколько товарных позиций (строк). Данные загружаются через YM API. Статусы: DELIVERED означает доставленный (выкупленный) заказ. Для аналитики продаж фильтруй по status_norm = 'DELIVERED'.",
        questions: &["Какова выручка Яндекс.Маркет за период?", "Топ товаров по заказам на YM", "Сколько заказов доставлено за месяц?", "Маржинальность по заказам YM"],
        related: &["a004_nomenclature", "a006_connection_mp", "a002_organization"],
    },
};

/// Field metadata array
pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "YmOrderId",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "document_no",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Номер заказа YM",
            label_en: Some("YM Order Number"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(160),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Числовой ID заказа в системе Яндекс.Маркет (orderId из YM API)."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "connection_id",
        rust_type: "String",
        field_type: FieldType::AggregateRef,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Магазин YM",
            label_en: Some("YM Shop"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(200),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("UUID подключения YM из a006_connection_mp. JOIN: a013_ym_order.connection_id = a006_connection_mp.id."),
        nested_fields: None,
        ref_aggregate: Some("a006_connection_mp"),
        enum_values: None,
    },
    FieldMetadata {
        name: "status_norm",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Статус",
            label_en: Some("Status"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Нормализованный статус заказа: 'DELIVERED' — доставлен/выкуплен (считается продажей), 'CANCELLED' — отменён. Для подсчёта продаж: WHERE status_norm = 'DELIVERED'."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "creation_date",
        rust_type: "Option<DateTime<Utc>>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Дата создания",
            label_en: Some("Creation Date"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: Some("datetime"),
            column_width: Some(160),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Дата создания заказа в YM. ISO 8601 TEXT. Для группировки по месяцам: strftime('%Y-%m', creation_date)."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "total_amount",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Сумма заказа",
            label_en: Some("Total Amount"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(140),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Общая сумма заказа из YM API. В рублях. Для выручки: SUM(total_amount) WHERE status_norm='DELIVERED'."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "items_total",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Стоимость товаров",
            label_en: Some("Items Total"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: Some(140),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Общая стоимость товаров в заказе без доставки (itemsTotal из YM API)."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "margin_pro",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Маржа %",
            label_en: Some("Margin %"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: false,
            widget: None,
            column_width: Some(100),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Маржинальность заказа в процентах. Заполняется при проведении. NULL если нет данных о себестоимости. (total_amount - себестоимость) / total_amount * 100."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "total_dealer_amount",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Сумма по дилерским ценам",
            label_en: Some("Total Dealer Amount"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: Some(180),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Итоговая сумма строк заказа по дилерским (закупочным) ценам из 1С. Заполняется при проведении."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "campaign_id",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "ID кампании YM",
            label_en: Some("YM Campaign ID"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("ID кампании (магазина) в Яндекс.Маркет API."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
