#![allow(dead_code)]

use crate::shared::metadata::{
    EntityAiMetadata, EntityMetadataInfo, EntityType, EntityUiMetadata, FieldMetadata, FieldSource,
    FieldType, FieldUiMetadata, ValidationRules,
};

pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Projection,
    entity_name: "MpSalesFunnelTurnover",
    entity_index: "p916",
    collection_name: "mp_sales_funnel_turnovers",
    table_name: Some("p916_mp_sales_funnel_turnovers"),
    ui: EntityUiMetadata {
        element_name: "Воронка продаж МП (движения)",
        element_name_en: Some("MP Sales Funnel Turnovers"),
        list_name: "Движения воронки продаж МП",
        list_name_en: Some("MP Sales Funnel Turnovers"),
        icon: Some("filter"),
    },
    ai: EntityAiMetadata {
        description: "Проекция-накопитель воронки продаж маркетплейсов: показы → переходы → корзина → заказ → выкуп, плюс отмены и возвраты. Модель — движения-обороты (как p909/p914): каждый регистратор пишет свои строки, агрегация метрик — SUM на чтении. Две стадии (поле stage): marketing (верх воронки, дневной агрегат nm_id×дата: open/cart/wishlist/funnel_order из a036; показы) и fulfillment (уровень заказа: order/cancel/buyout/return из a015 и a012). Две оси дат: cohort_date (когорта = дата заказа) и event_date (дата события/транзакции). Показы: show_paid_count — платные (реклама a026, metrics.views, пишется при ПРОВЕДЕНИИ a026); show_free_count — органические, но источник пока не подключён (a040 отдаёт только visibility %, не счётчик), поэтому всегда NULL/N/A. Всего показов не хранится — считается на чтении COALESCE(free,0)+COALESCE(paid,0). Отменённый заказ порождает ДВЕ строки: order (order_count=1) и cancel (cancel_count=1). Конверсии не хранятся, считаются на чтении. Потребитель — дашборд d406_wb_sales_funnel; агрегатор — aggregate_by_product с выбором оси (cohort/event).",
        questions: &[
            "Какая воронка продаж WB за период (показы→переходы→корзина→заказ→выкуп)?",
            "Сколько заказов, отмен, выкупов и возвратов по товару за период?",
            "Какая доля отмен и конверсия в выкуп по когорте заказов?",
            "Сколько платных (рекламных) показов у товара по дням?",
            "Чем отличается когортная ось (по дате заказа) от потоковой (по дате события)?",
        ],
        related: &[
            "a036_wb_sales_funnel_daily",
            "a015_wb_orders",
            "a012_wb_sales",
            "a026_wb_advert_daily",
            "a006_connection_mp",
            "a007_marketplace_product",
            "a004_nomenclature",
        ],
    },
    access: None,
};

pub const FIELDS: &[FieldMetadata] = &[
    field(
        "id",
        "String",
        "ID",
        true,
        true,
        Some("Детерминированный uuid v5 строки движения (натуральный ключ: registrator_type|registrator_ref|stage|kind|cohort_date|event_date|connection_mp_ref|товар)."),
        None,
        None,
    ),
    field(
        "stage",
        "String",
        "Stage",
        true,
        true,
        Some("Стадия воронки: marketing (верх — a036/a026) или fulfillment (заказ→завершение — a015/a012)."),
        None,
        Some(&["marketing", "fulfillment"]),
    ),
    field(
        "cohort_date",
        "String",
        "Cohort Date",
        true,
        true,
        Some("Ось когорты (винтаж) = дата заказа. Для стадии marketing — день воронки. YYYY-MM-DD."),
        None,
        None,
    ),
    field(
        "event_date",
        "String",
        "Event Date",
        true,
        true,
        Some("Ось потока = дата транзакции события (напр. дата отмены). Для стадии marketing = cohort_date. YYYY-MM-DD."),
        None,
        None,
    ),
    field(
        "connection_mp_ref",
        "String",
        "Connection",
        true,
        true,
        Some("UUID кабинета маркетплейса."),
        Some("a006_connection_mp"),
        None,
    ),
    field(
        "marketplace_product_ref",
        "Option<String>",
        "Marketplace Product",
        false,
        false,
        Some("Ссылка на a007_marketplace_product (у стадии marketing из a036 может отсутствовать)."),
        Some("a007_marketplace_product"),
        None,
    ),
    field(
        "nomenclature_ref",
        "Option<String>",
        "Nomenclature",
        false,
        false,
        Some("Ссылка на a004_nomenclature."),
        Some("a004_nomenclature"),
        None,
    ),
    field(
        "nm_id",
        "Option<i64>",
        "nm_id",
        true,
        false,
        Some("WB-native артикул (мост между стадиями воронки)."),
        None,
        None,
    ),
    field(
        "registrator_type",
        "String",
        "Registrator Type",
        true,
        true,
        Some("Тип документа-источника: a036_wb_sales_funnel_daily, a026_wb_advert_daily, a015_wb_orders, a012_wb_sales."),
        None,
        None,
    ),
    field(
        "registrator_ref",
        "String",
        "Registrator Ref",
        true,
        true,
        Some("Ссылка на документ-источник (id; у a015/a012 — префикс a015:/a012:)."),
        None,
        None,
    ),
    field(
        "show_free_count",
        "Option<i64>",
        "Show Free",
        true,
        false,
        Some("Бесплатные/органические показы. Источник пока не подключён (a040 исключён), поэтому обычно NULL/N/A."),
        None,
        None,
    ),
    field(
        "show_paid_count",
        "Option<i64>",
        "Show Paid",
        true,
        false,
        Some("Платные (рекламные) показы из a026 (metrics.views); пишется при проведении a026. NULL = нет данных."),
        None,
        None,
    ),
    field(
        "open_count",
        "i64",
        "Opens",
        true,
        false,
        Some("Переходы в карточку (стадия marketing, a036)."),
        None,
        None,
    ),
    field(
        "cart_count",
        "i64",
        "Cart",
        true,
        false,
        Some("Добавления в корзину (a036)."),
        None,
        None,
    ),
    field(
        "wishlist_count",
        "i64",
        "Wishlist",
        false,
        false,
        Some("Добавления в избранное (a036)."),
        None,
        None,
    ),
    field(
        "funnel_order_count",
        "i64",
        "Funnel Orders",
        true,
        false,
        Some("Заказы по счётчику воронки a036 (маркетинговый счётчик ≠ фактические заказы стадии fulfillment)."),
        None,
        None,
    ),
    field(
        "funnel_order_sum",
        "f64",
        "Funnel Orders Sum",
        false,
        false,
        Some("Сумма заказов по счётчику воронки a036."),
        None,
        None,
    ),
    field(
        "order_count",
        "i64",
        "Orders",
        true,
        false,
        Some("Фактические заказы (стадия fulfillment, a015). Отменённый заказ всё равно даёт строку order."),
        None,
        None,
    ),
    field(
        "order_sum",
        "f64",
        "Orders Sum",
        true,
        false,
        Some("Сумма фактических заказов (a015)."),
        None,
        None,
    ),
    field(
        "cancel_count",
        "i64",
        "Cancels",
        true,
        false,
        Some("Отмены заказов (a015). Отдельная строка kind=cancel, cohort_date=дата заказа, event_date=дата отмены."),
        None,
        None,
    ),
    field(
        "cancel_sum",
        "f64",
        "Cancels Sum",
        false,
        false,
        Some("Сумма отмен (a015)."),
        None,
        None,
    ),
    field(
        "buyout_count",
        "i64",
        "Buyouts",
        true,
        false,
        Some("Выкупы (a012). Когорта резолвится по srid к дате заказа a015."),
        None,
        None,
    ),
    field(
        "buyout_sum",
        "f64",
        "Buyouts Sum",
        false,
        false,
        Some("Сумма выкупов (a012)."),
        None,
        None,
    ),
    field(
        "return_count",
        "i64",
        "Returns",
        true,
        false,
        Some("Возвраты (a012)."),
        None,
        None,
    ),
    field(
        "return_sum",
        "f64",
        "Returns Sum",
        false,
        false,
        Some("Сумма возвратов (a012)."),
        None,
        None,
    ),
    field(
        "created_at_msk",
        "String",
        "Created At (MSK)",
        false,
        false,
        Some("Время создания строки проекции (MSK)."),
        None,
        None,
    ),
    field(
        "updated_at_msk",
        "String",
        "Updated At (MSK)",
        false,
        false,
        Some("Время последнего обновления строки проекции (MSK)."),
        None,
        None,
    ),
];

const fn field(
    name: &'static str,
    rust_type: &'static str,
    label: &'static str,
    visible_in_list: bool,
    required: bool,
    ai_hint: Option<&'static str>,
    ref_aggregate: Option<&'static str>,
    enum_values: Option<&'static [&'static str]>,
) -> FieldMetadata {
    FieldMetadata {
        name,
        rust_type,
        field_type: if ref_aggregate.is_some() {
            FieldType::AggregateRef
        } else if enum_values.is_some() {
            FieldType::Enum
        } else {
            FieldType::Primitive
        },
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label,
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint,
        nested_fields: None,
        ref_aggregate,
        enum_values,
    }
}
