// ============================================================================
// AUTO-GENERATED FROM metadata.json - DO NOT EDIT MANUALLY
// Generated: 2026-02-25T21:21:20Z
// ============================================================================

#![allow(dead_code)]

use crate::shared::metadata::{
    EntityMetadataInfo, EntityType, EntityUiMetadata, EntityAiMetadata,
    FieldMetadata, FieldType, FieldSource, FieldUiMetadata, ValidationRules
};

/// Entity metadata for ConnectionMP aggregate
pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Aggregate,
    entity_name: "ConnectionMP",
    entity_index: "a006",
    collection_name: "connection_mp",
    table_name: Some("a006_connection_mp"),
    ui: EntityUiMetadata {
        element_name: "Подключение маркетплейса",
        element_name_en: Some("Marketplace Connection"),
        list_name: "Подключения маркетплейсов",
        list_name_en: Some("Marketplace Connections"),
        icon: Some("plug"),
    },
    ai: EntityAiMetadata {
        description: "Подключения к торговым площадкам — один магазин на WB, Ozon или Яндекс.Маркет. Содержит API-ключи и идентификаторы магазинов. Используется как основной идентификатор магазина во всех документах продаж. Поле description содержит понятное название магазина.",
        questions: &["Сколько магазинов подключено?", "Какие магазины WB есть в системе?", "Какой connection_id у магазина X?", "Какая выручка по каждому магазину?"],
        related: &["a002_organization", "a005_marketplace", "a012_wb_sales", "a013_ym_order"],
    },
};

/// Field metadata array
pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "ConnectionMPId",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("UUID подключения. Используется как FK в a012_wb_sales (connection_id), a013_ym_order (connection_id) и в проекциях (connection_mp_ref)."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "code",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Код",
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "description",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Название магазина",
            label_en: Some("Shop Name"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(250),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Понятное название магазина (например: 'WB - Основной магазин', 'Ozon - ИП Иванов'). Для отображения в отчётах: JOIN с a006_connection_mp по connection_id = id."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "marketplace_id",
        rust_type: "String",
        field_type: FieldType::AggregateRef,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Маркетплейс",
            label_en: Some("Marketplace"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("UUID маркетплейса из a005_marketplace. JOIN: a006_connection_mp.marketplace_id = a005_marketplace.id."),
        nested_fields: None,
        ref_aggregate: Some("a005_marketplace"),
        enum_values: None,
    },
    FieldMetadata {
        name: "organization_ref",
        rust_type: "String",
        field_type: FieldType::AggregateRef,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Организация",
            label_en: Some("Organization"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(200),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("UUID организации из a002_organization. JOIN: a006_connection_mp.organization_ref = a002_organization.id."),
        nested_fields: None,
        ref_aggregate: Some("a002_organization"),
        enum_values: None,
    },
    FieldMetadata {
        name: "is_used",
        rust_type: "bool",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Используется",
            label_en: Some("Is Used"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("checkbox"),
            column_width: Some(100),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("true если подключение активно и используется для получения данных."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "planned_commission_percent",
        rust_type: "Option<f64>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Плановая комиссия %",
            label_en: Some("Planned Commission %"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Плановый процент комиссии маркетплейса для этого магазина. Используется в расчёте плановой прибыли."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
