// ============================================================================
// AUTO-GENERATED FROM metadata.json - DO NOT EDIT MANUALLY
// Generated: 2026-01-20T20:58:45Z
// ============================================================================

#![allow(dead_code)]

use crate::shared::metadata::{
    EntityMetadataInfo, EntityType, EntityUiMetadata, EntityAiMetadata,
    FieldMetadata, FieldType, FieldSource, FieldUiMetadata, ValidationRules
};

/// Entity metadata for LlmAgent aggregate
pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Aggregate,
    entity_name: "LlmAgent",
    entity_index: "a017",
    collection_name: "llm_agent",
    table_name: Some("a017_llm_agent"),
    ui: EntityUiMetadata {
        element_name: "Агент LLM",
        element_name_en: Some("LLM Agent"),
        list_name: "Агенты LLM",
        list_name_en: Some("LLM Agents"),
        icon: Some("robot"),
    },
    ai: EntityAiMetadata {
        description: "Настройки подключения к провайдерам LLM (OpenAI, Anthropic, Ollama). Содержит API ключи, параметры модели (temperature, max_tokens) и системный промпт. Используется для создания чатов и выполнения запросов к языковым моделям.",
        questions: &["Какие LLM агенты настроены?", "Как добавить OpenAI агента?", "Какие параметры можно настроить для агента?", "Как изменить температуру модели?"],
        related: &["a018_llm_chat", "a019_llm_artifact"],
    },
};

/// Field metadata array
pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "LlmAgentId",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID",
            label_en: Some("ID"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "code",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Код",
            label_en: Some("Code"),
            placeholder: Some("GPT4O-MAIN"),
            hint: Some("Уникальный код агента"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(50),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "description",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Наименование",
            label_en: Some("Name"),
            placeholder: Some("GPT-4o основной агент"),
            hint: Some("Описательное название агента"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(250),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: Some(3),
            max_length: Some(255),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "comment",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "Комментарий",
            label_en: Some("Comment"),
            placeholder: Some("Используется для анализа продаж"),
            hint: Some("Произвольный комментарий"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(1000),
            pattern: None,
            custom_error: None,
        },
        ai_hint: None,
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "provider_type",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Провайдер",
            label_en: Some("Provider"),
            placeholder: None,
            hint: Some("Тип провайдера LLM"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("select"),
            column_width: Some(120),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Поддерживаемые провайдеры: OpenAI (GPT-4, GPT-4o), Anthropic (Claude), Ollama (локальные модели)"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "api_endpoint",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "API Endpoint",
            label_en: Some("API Endpoint"),
            placeholder: Some("https://api.openai.com/v1"),
            hint: Some("URL эндпоинта API провайдера"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: Some(300),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(500),
            pattern: Some("^https?://.+"),
            custom_error: Some("URL должен начинаться с http:// или https://"),
        },
        ai_hint: Some("OpenAI: https://api.openai.com/v1, Anthropic: https://api.anthropic.com, Ollama: http://localhost:11434"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "api_key",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "API Ключ",
            label_en: Some("API Key"),
            placeholder: Some("sk-..."),
            hint: Some("API ключ для аутентификации"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("password"),
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(500),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Хранится в зашифрованном виде. Для OpenAI формат: sk-..."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "model_name",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Модель",
            label_en: Some("Model"),
            placeholder: Some("gpt-4o"),
            hint: Some("Название модели"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(150),
        },
        validation: ValidationRules {
            required: true,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(100),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("OpenAI: gpt-4o, gpt-4-turbo, gpt-3.5-turbo. Anthropic: claude-3-5-sonnet-20241022. Ollama: llama3.2, mistral"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "available_models",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Доступные модели",
            label_en: Some("Available Models"),
            placeholder: None,
            hint: Some("JSON список моделей из API"),
            visible_in_list: false,
            visible_in_form: false,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("JSON массив объектов с полями: id, created, owned_by. Загружается из /v1/models API провайдера."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "temperature",
        rust_type: "f64",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Temperature",
            label_en: Some("Temperature"),
            placeholder: Some("0.7"),
            hint: Some("Креативность ответов (0.0-2.0)"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: Some(0.0),
            max: Some(2.0),
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("0.0 - детерминированные ответы, 1.0 - сбалансированно, 2.0 - максимально креативно"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "max_tokens",
        rust_type: "i32",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Max Tokens",
            label_en: Some("Max Tokens"),
            placeholder: Some("4096"),
            hint: Some("Максимальная длина ответа"),
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required: true,
            min: Some(256.0),
            max: Some(128000.0),
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("GPT-4o поддерживает до 128k токенов, GPT-3.5 - до 16k"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "system_prompt",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Системный промпт",
            label_en: Some("System Prompt"),
            placeholder: Some("Ты аналитик данных маркетплейсов..."),
            hint: Some("Базовая инструкция для агента"),
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("textarea"),
            column_width: None,
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: Some(5000),
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Определяет роль и поведение агента. Например: 'Ты эксперт по SQL и аналитике маркетплейсов. Отвечай кратко и точно.'"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "is_primary",
        rust_type: "bool",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Основной",
            label_en: Some("Primary"),
            placeholder: None,
            hint: Some("Использовать по умолчанию"),
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("checkbox"),
            column_width: Some(100),
        },
        validation: ValidationRules {
            required: false,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint: Some("Только один агент может быть основным. При установке флага автоматически снимается с других агентов."),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
