//! BI Indicator Domain Module
//!
//! Индикаторы BI-дашбордов. Один агрегат = один индикатор.
//! Содержит спецификации данных (DataSpec), параметров (Params),
//! отображения (ViewSpec) и drill-down навигации (DrillSpec).

pub mod aggregate;

// Generated by build.rs from metadata.json
#[allow(dead_code)]
mod metadata_gen;
pub use metadata_gen::{ENTITY_METADATA, FIELDS};

pub use aggregate::{
    BiIndicator, BiIndicatorId, BiIndicatorListItem, BiIndicatorStatus, DataSpec, DrillSpec,
    DrillTarget, ParamDef, ParamType, Threshold, ViewSpec,
};
