#![allow(deprecated)]

use contracts::shared::universal_dashboard::{DataSourceSchema, FieldDef, FieldType};

/// P903 WB Finance Report schema definition
pub static P903_SCHEMA: DataSourceSchema = DataSourceSchema {
    id: "p903_wb_finance_report",
    name: "WB Finance Report",
    fields: &[
        // Grouping fields
        FieldDef {
            id: "rr_dt",
            name: "Дата",
            field_type: FieldType::Date,
            can_group: true,
            can_aggregate: false,
            db_column: "rr_dt",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "nm_id",
            name: "Артикул WB",
            field_type: FieldType::Integer,
            can_group: true,
            can_aggregate: false,
            db_column: "nm_id",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "sa_name",
            name: "Артикул продавца",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "sa_name",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "subject_name",
            name: "Категория товара",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "subject_name",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "supplier_oper_name",
            name: "Тип операции",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "supplier_oper_name",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "bonus_type_name",
            name: "Тип бонуса",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "bonus_type_name",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "connection_mp_ref",
            name: "Подключение",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "connection_mp_ref",
            ref_table: Some("a006_connection_mp"),
            ref_display_column: Some("description"),
        },
        FieldDef {
            id: "organization_ref",
            name: "Организация",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "organization_ref",
            ref_table: Some("a002_organization"),
            ref_display_column: Some("description"),
        },
        // Numeric fields (can aggregate)
        FieldDef {
            id: "retail_amount",
            name: "Сумма продаж",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "retail_amount",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "retail_price",
            name: "Розничная цена",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "retail_price",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "quantity",
            name: "Количество",
            field_type: FieldType::Integer,
            can_group: false,
            can_aggregate: true,
            db_column: "quantity",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "ppvz_for_pay",
            name: "К перечислению продавцу",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "ppvz_for_pay",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "commission_percent",
            name: "Комиссия %",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "commission_percent",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "delivery_rub",
            name: "Стоимость доставки",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "delivery_rub",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "storage_fee",
            name: "Стоимость хранения",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "storage_fee",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "penalty",
            name: "Штрафы",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "penalty",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "acquiring_fee",
            name: "Эквайринг",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "acquiring_fee",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "return_amount",
            name: "Сумма возвратов",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "return_amount",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "ppvz_sales_commission",
            name: "Комиссия продажи",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "ppvz_sales_commission",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "additional_payment",
            name: "Доплаты",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "additional_payment",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "cashback_amount",
            name: "Кэшбэк",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "cashback_amount",
            ref_table: None,
            ref_display_column: None,
        },
        FieldDef {
            id: "rebill_logistic_cost",
            name: "Логистика",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "rebill_logistic_cost",
            ref_table: None,
            ref_display_column: None,
        },
    ],
};
