use contracts::shared::analytics::{
    AggKind, ReportGroup, SelectionRule, SignPolicy, TurnoverClassDef, TurnoverScope, ValueKind,
};

pub const TURNOVER_CLASSES: &[TurnoverClassDef] = &[
    TurnoverClassDef {
        code: "qty_ordered",
        name: "Количество заказано",
        description: "Количество строк заказа на операционном слое заказов.",
        llm_description: "Сколько единиц было заказано по строке заказа.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Quantity,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::OperOnly,
        sign_policy: SignPolicy::IncomePositive,
        report_group: ReportGroup::Quantity,
        aliases: &["ordered_qty", "qty_order"],
        source_examples: &["a015_wb_orders.line.qty"],
        formula_hint: "amount where layer=oper",
        notes: "Для WB v1 заполняется из a015_wb_orders.",
        debit_account: "",
        credit_account: "",
        generates_journal_entry: false,
        journal_comment: "Количество единиц товара, зарезервированных в заказе. Источник: a015_wb_orders.line.qty. В журнале не отражается.",
    },
    TurnoverClassDef {
        code: "qty_sold",
        name: "Количество продано",
        description: "Количество реализованных единиц по строке заказа.",
        llm_description: "Проданное количество по строке заказа.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Quantity,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::PreferFact,
        sign_policy: SignPolicy::IncomePositive,
        report_group: ReportGroup::Quantity,
        aliases: &["sold_qty"],
        source_examples: &["a012_wb_sales.line.qty", "p903_wb_finance_report.quantity"],
        formula_hint: "prefer amount where layer=fact, else layer=oper",
        notes: "Для WB return не используется, для возврата отдельный turnover_code.",
        debit_account: "",
        credit_account: "",
        generates_journal_entry: false,
        journal_comment: "Количество реализованных единиц товара по строке продажи. Источник: a012_wb_sales.line.qty. В журнале не отражается.",
    },
    TurnoverClassDef {
        code: "qty_returned",
        name: "Количество возвращено",
        description: "Количество единиц, возвращенных покупателем.",
        llm_description: "Возврат количества по строке заказа.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Quantity,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::PreferFact,
        sign_policy: SignPolicy::IncomePositive,
        report_group: ReportGroup::Quantity,
        aliases: &["returned_qty"],
        source_examples: &["a012_wb_sales.line.qty", "p903_wb_finance_report.quantity"],
        formula_hint: "prefer amount where layer=fact, else layer=oper",
        notes: "Хранится отдельным оборотом с положительным количеством.",
        debit_account: "",
        credit_account: "",
        generates_journal_entry: false,
        journal_comment: "Количество единиц товара, возвращённых покупателем. Тип события = return. В журнале не отражается.",
    },
    TurnoverClassDef {
        code: "customer_revenue",
        name: "Выручка от покупателя",
        description: "Поступление от продажи по строке заказа.",
        llm_description: "Выручка от продажи по строке заказа.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::PreferFact,
        sign_policy: SignPolicy::IncomePositive,
        report_group: ReportGroup::Revenue,
        aliases: &["revenue", "customer_in"],
        source_examples: &["a012_wb_sales.line.price_effective"],
        formula_hint: "prefer amount where layer=fact, else layer=oper",
        notes: "Расчёты через маркетплейс: WB обязан перечислить продавцу сумму выручки.",
        debit_account: "7609",
        credit_account: "9001",
        generates_journal_entry: true,
        journal_comment: "Выручка по цене продавца до скидки СПП. Сумма = price_effective. Покупатель платит WB, поэтому дебетуется счёт расчётов с маркетплейсом. Дт7609 / Кт9001.",
    },
    TurnoverClassDef {
        code: "customer_return",
        name: "Возврат покупателю",
        description: "Сумма возврата по строке заказа.",
        llm_description: "Отрицательная выручка для возврата по строке заказа.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::PreferFact,
        sign_policy: SignPolicy::Natural,
        report_group: ReportGroup::Returns,
        aliases: &["return", "customer_out"],
        source_examples: &["a012_wb_sales.line.price_effective (return)"],
        formula_hint: "prefer amount where layer=fact, else layer=oper",
        notes: "Хранится как отрицательная сумма. Сторно выручки через счёт маркетплейса.",
        debit_account: "9001",
        credit_account: "7609",
        generates_journal_entry: true,
        journal_comment: "Сторнирование выручки при возврате товара. Сумма = price_effective. Уменьшает выручку и задолженность WB перед продавцом. Дт9001 / Кт7609.",
    },
    TurnoverClassDef {
        code: "seller_payout",
        name: "Выплата продавцу",
        description: "Сумма, которую маркетплейс перечисляет продавцу по строке.",
        llm_description: "Фактическая или плановая выплата продавцу.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::PreferFact,
        sign_policy: SignPolicy::IncomePositive,
        report_group: ReportGroup::Payout,
        aliases: &["payout", "ppvz_for_pay"],
        source_examples: &["a012_wb_sales.line.supplier_payout_plan", "p903_wb_finance_report.ppvz_for_pay"],
        formula_hint: "prefer amount where layer=fact, else layer=oper",
        notes: "Для возврата может становиться отрицательной. Счёт расчётного счёта не определён в текущем плане счетов.",
        debit_account: "",
        credit_account: "",
        generates_journal_entry: false,
        journal_comment: "Итоговая сумма к перечислению продавцу после всех удержаний WB. Источник: supplier_payout_plan / ppvz_for_pay. Справочный оборот, в журнале не отражается.",
    },
    TurnoverClassDef {
        code: "mp_commission",
        name: "Комиссия маркетплейса",
        description: "Комиссия маркетплейса по строке заказа или непривязанной операции.",
        llm_description: "Расход на комиссию маркетплейса.",
        scope: TurnoverScope::Both,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::PreferFact,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Commission,
        aliases: &["commission", "ppvz_vw", "ppvz_sales_commission"],
        source_examples: &["finished_price - amount_line, если результат > 0"],
        formula_hint: "prefer amount where layer=fact, else layer=oper",
        notes: "Формула: finished_price − amount_line (только если > 0). WB берёт маржу сверх цены продавца. Взаимоисключает wb_coinvestment.",
        debit_account: "4401",
        credit_account: "7609",
        generates_journal_entry: true,
        journal_comment: "Комиссия WB: разница, когда покупатель заплатил больше цены продавца. Формула: finished_price − amount_line > 0. Взаимоисключает соинвестирование. Дт4401 / Кт7609.",
    },
    TurnoverClassDef {
        code: "mp_commission_adjustment",
        name: "Корректировка комиссии WB",
        description: "Корректировка комиссии WB по логистическим и прочим причинам.",
        llm_description: "Фактовая корректировка комиссии WB для операций, которые не являются продажей или возвратом.",
        scope: TurnoverScope::Both,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::FactOnly,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Adjustment,
        aliases: &["commission_adjustment"],
        source_examples: &["p903_wb_finance_report.ppvz_vw + p903_wb_finance_report.ppvz_vw_nds + p903_wb_finance_report.ppvz_sales_commission"],
        formula_hint: "amount where layer=fact and supplier_oper_name not in ('Продажа', 'Возврат')",
        notes: "Используется для p903-строк с корректировками комиссии по логистическим и прочим причинам.",
        debit_account: "4402",
        credit_account: "7609",
        generates_journal_entry: true,
        journal_comment: "Корректировка комиссии WB по логистическим и прочим причинам. Источник: p903 non-sale/non-return commission fields. Дт4402 / Кт7609.",
    },
    TurnoverClassDef {
        code: "mp_acquiring",
        name: "Эквайринг маркетплейса",
        description: "Расход на эквайринг по строке заказа.",
        llm_description: "Эквайринг по продаже или возврату.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::PreferFact,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Acquiring,
        aliases: &["acquiring"],
        source_examples: &["a012_wb_sales.line.acquiring_fee_plan", "p903_wb_finance_report.acquiring_fee"],
        formula_hint: "prefer amount where layer=fact, else layer=oper",
        notes: "Формула: finished_price * acquiring_fee_pro% / 100. Хранится положительной суммой.",
        debit_account: "4403",
        credit_account: "7609",
        generates_journal_entry: true,
        journal_comment: "Эквайринг маркетплейса. Источник: acquiring_fee. Дт4403 / Кт7609. Для возвратов в p903 отражается со знаком минус.",
    },
    TurnoverClassDef {
        code: "mp_logistics",
        name: "Логистика маркетплейса",
        description: "Логистические удержания по строке или непривязанной операции.",
        llm_description: "Логистический расход маркетплейса.",
        scope: TurnoverScope::Both,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::PreferFact,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Logistics,
        aliases: &["logistics", "delivery_rub"],
        source_examples: &["a012_wb_sales.line.other_fee_plan", "p903_wb_finance_report.delivery_rub"],
        formula_hint: "prefer amount where layer=fact, else layer=oper",
        notes: "WB v1 использует только факт для большинства логистических удержаний.",
        debit_account: "4404",
        credit_account: "7609",
        generates_journal_entry: true,
        journal_comment: "Логистические услуги WB по операциям «Логистика» и «Коррекция логистики». Источник: delivery_rub. Дт4404 / Кт7609.",
    },
    TurnoverClassDef {
        code: "mp_storage",
        name: "Хранение маркетплейса",
        description: "Удержания за хранение без обязательной привязки к заказу.",
        llm_description: "Расход на хранение в маркетплейсе.",
        scope: TurnoverScope::Both,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::FactOnly,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Storage,
        aliases: &["storage", "storage_fee"],
        source_examples: &["p903_wb_finance_report.storage_fee"],
        formula_hint: "amount where layer=fact",
        notes: "Для WB v1 источник только p903.",
        debit_account: "4404",
        credit_account: "7609",
        generates_journal_entry: true,
        journal_comment: "Плата за хранение товара на складе WB. Источник: storage_fee. Дт4404 / Кт7609.",
    },
    TurnoverClassDef {
        code: "mp_penalty",
        name: "Штраф маркетплейса",
        description: "Штрафы и санкции маркетплейса.",
        llm_description: "Штраф или санкция маркетплейса.",
        scope: TurnoverScope::Both,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::FactOnly,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Penalty,
        aliases: &["penalty"],
        source_examples: &["p903_wb_finance_report.penalty"],
        formula_hint: "amount where layer=fact",
        notes: "В WB v1 приходит из p903.",
        debit_account: "9102",
        credit_account: "7609",
        generates_journal_entry: true,
        journal_comment: "Штрафы и санкции WB. Источник: penalty > 0 в p903. Дт9102 / Кт7609.",
    },
    TurnoverClassDef {
        code: "mp_penalty_reversal",
        name: "Отмена штрафа маркетплейса",
        description: "Сторно или отмена ранее начисленного штрафа WB.",
        llm_description: "Отмена штрафа WB, которая восстанавливает прочий доход.",
        scope: TurnoverScope::Both,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::FactOnly,
        sign_policy: SignPolicy::IncomePositive,
        report_group: ReportGroup::Penalty,
        aliases: &["penalty_reversal", "penalty_cancel"],
        source_examples: &["p903_wb_finance_report.penalty < 0"],
        formula_hint: "amount where layer=fact and penalty < 0",
        notes: "Используется, чтобы отдельно видеть начисление штрафа и его отмену.",
        debit_account: "7609",
        credit_account: "9102",
        generates_journal_entry: true,
        journal_comment: "Отмена ранее начисленного штрафа WB. Источник: penalty < 0 в p903. Дт7609 / Кт9102.",
    },
    TurnoverClassDef {
        code: "mp_transport_storage_reimbursement",
        name: "Возмещение издержек по перевозке и складским операциям",
        description: "Отдельный оборот для незаполненного SRID по операции возмещения издержек по перевозке/по складским операциям с товаром.",
        llm_description: "Непривязанное возмещение издержек по перевозке и складским операциям, которое нужно видеть отдельной строкой отчёта.",
        scope: TurnoverScope::Unlinked,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::FactOnly,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Logistics,
        aliases: &["transport_storage_reimbursement"],
        source_examples: &["p903_wb_finance_report.supplier_oper_name = 'Возмещение издержек по перевозке/по складским операциям с товаром' and srid is empty"],
        formula_hint: "amount where layer=fact and supplier_oper_name matches reimbursement operation and srid is empty",
        notes: "Проводки те же, что и для логистики/хранения, но turnover_code отдельный для аналитики отчёта.",
        debit_account: "4404",
        credit_account: "7609",
        generates_journal_entry: true,
        journal_comment: "Возмещение издержек по перевозке/по складским операциям с товаром без SRID. Отдельный оборот для отчётности. Дт4404 / Кт7609.",
    },
    TurnoverClassDef {
        code: "item_cost",
        name: "Себестоимость",
        description: "Себестоимость единицы или строки заказа по дилерской цене УТ.",
        llm_description: "Себестоимость товара по строке заказа.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::OperOnly,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Cost,
        aliases: &["cost", "dealer_price_ut"],
        source_examples: &["a012_wb_sales.line.dealer_price_ut"],
        formula_hint: "amount where layer=oper",
        notes: "Формула: dealer_price_ut * qty (или cost_of_production * qty). Хранится положительной суммой.",
        debit_account: "9002",
        credit_account: "41",
        generates_journal_entry: true,
        journal_comment: "Себестоимость реализованного товара: dealer_price_ut × qty (приоритет) или cost_of_production × qty. Списание с товарного счёта. Дт9002 / Кт41.",
    },
    TurnoverClassDef {
        code: "spp_discount",
        name: "Скидка SPP (продажа)",
        description: "Скидка продавца (SPP) — сторно части выручки по цене продавца, приводит реализацию к finished_price.",
        llm_description: "Скидка продавца в рамках программы СПП маркетплейса.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::OperOnly,
        sign_policy: SignPolicy::Natural,
        report_group: ReportGroup::Returns,
        aliases: &["spp"],
        source_examples: &["a012_wb_sales.line.price_effective * a012_wb_sales.line.spp / 100"],
        formula_hint: "amount where layer=oper",
        notes: "Сумма = -(price_effective * spp% / 100). Хранится отрицательной. В журнале красное сторно: Дт7609/Кт9001 с отрицательной суммой.",
        debit_account: "7609",
        credit_account: "9001",
        generates_journal_entry: true,
        journal_comment: "Красное сторно части выручки на скидку СПП. Формула: -(price_effective × spp% / 100). Сумма отрицательная. Дт7609 / Кт9001.",
    },
    TurnoverClassDef {
        code: "spp_discount_return",
        name: "Скидка SPP (возврат)",
        description: "Восстановление скидки SPP при возврате — увеличивает выручку и задолженность маркетплейса.",
        llm_description: "Восстановление скидки SPP при возврате.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::OperOnly,
        sign_policy: SignPolicy::IncomePositive,
        report_group: ReportGroup::Returns,
        aliases: &["spp_return"],
        source_examples: &["a012_wb_sales.line.price_effective * a012_wb_sales.line.spp / 100 (return)"],
        formula_hint: "amount where layer=oper",
        notes: "Сторнирует spp_discount при возврате: Дт7609/Кт9001, положительная сумма.",
        debit_account: "7609",
        credit_account: "9001",
        generates_journal_entry: true,
        journal_comment: "Восстановление скидки СПП при возврате товара. Формула: price_effective × spp% / 100. Сторнирует spp_discount. Дт7609 / Кт9001.",
    },
    TurnoverClassDef {
        code: "wb_coinvestment",
        name: "Соинвестирование WB (продажа)",
        description: "Компенсация от маркетплейса: разница между amount_line и finished_price.",
        llm_description: "Дополнительный доход от WB: субсидия разницы между ценой продавца и ценой покупателя.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::OperOnly,
        sign_policy: SignPolicy::IncomePositive,
        report_group: ReportGroup::Revenue,
        aliases: &["coinvestment", "wb_subsidy"],
        source_examples: &["amount_line - finished_price, если результат > 0"],
        formula_hint: "amount where layer=oper",
        notes: "Формула: amount_line − finished_price (только если > 0). WB компенсирует разницу продавцу. Взаимоисключает mp_commission.",
        debit_account: "7609",
        credit_account: "91",
        generates_journal_entry: true,
        journal_comment: "Субсидия WB: покупатель заплатил меньше цены продавца — WB компенсирует разницу. Формула: amount_line − finished_price > 0. Взаимоисключает комиссию. Дт7609 / Кт91.",
    },
    TurnoverClassDef {
        code: "wb_coinvestment_return",
        name: "Соинвестирование WB (возврат)",
        description: "Сторнирование соинвестирования WB при возврате товара.",
        llm_description: "Восстановление соинвестирования WB при возврате.",
        scope: TurnoverScope::OrderLine,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::OperOnly,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Returns,
        aliases: &["coinvestment_return"],
        source_examples: &["amount_line - finished_price (return)"],
        formula_hint: "amount where layer=oper",
        notes: "Сторнирует wb_coinvestment при возврате: Дт91/Кт7609.",
        debit_account: "91",
        credit_account: "7609",
        generates_journal_entry: true,
        journal_comment: "Сторнирование субсидии WB при возврате товара. Уменьшает прочие доходы (91) и задолженность WB (7609). Дт91 / Кт7609.",
    },
    TurnoverClassDef {
        code: "advertising_allocated",
        name: "Рекламные расходы по номенклатуре",
        description: "Оперативные расходы на рекламу WB, распределенные по номенклатуре.",
        llm_description: "Рекламный расход WB по конкретной номенклатуре и кабинету.",
        scope: TurnoverScope::Nomenclature,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::OperOnly,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Advertising,
        aliases: &["wb_advertising", "ad_spend_allocated"],
        source_examples: &["a026_wb_advert_daily.lines[].metrics.sum"],
        formula_hint: "amount where layer=oper",
        notes: "Используется для распределенных расходов WB Ads по номенклатуре. Одна строка a026 = одна строка p911.",
        debit_account: "4401",
        credit_account: "7609",
        generates_journal_entry: true,
        journal_comment: "Рекламные расходы Wildberries, распределенные по номенклатуре. Источник: a026_wb_advert_daily.lines[].metrics.sum. Проводка Дт4401 / Кт7609.",
    },
    TurnoverClassDef {
        code: "advertising",
        name: "Реклама",
        description: "Рекламные удержания или начисления маркетплейса.",
        llm_description: "Рекламный расход или корректировка.",
        scope: TurnoverScope::Unlinked,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::FactOnly,
        sign_policy: SignPolicy::Natural,
        report_group: ReportGroup::Advertising,
        aliases: &["ads"],
        source_examples: &["p903_wb_finance_report.bonus_type_name=Реклама"],
        formula_hint: "amount where layer=fact",
        notes: "WB v1 пока почти не использует, оставлен для классификатора.",
        debit_account: "",
        credit_account: "",
        generates_journal_entry: false,
        journal_comment: "Рекламные расходы маркетплейса (промо-акции, продвижение). Источник: отчёт WB с типом операции «Реклама». В журнале не отражается.",
    },
    TurnoverClassDef {
        code: "acceptance",
        name: "Приемка",
        description: "Затраты на приемку или обработку поставок.",
        llm_description: "Расход на приемку или обработку.",
        scope: TurnoverScope::Unlinked,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::FactOnly,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Adjustment,
        aliases: &["acceptance_fee"],
        source_examples: &["p903_wb_finance_report.delivery_amount"],
        formula_hint: "amount where layer=fact",
        notes: "Используется как нормализованный bucket для delivery_amount.",
        debit_account: "4401",
        credit_account: "7609",
        generates_journal_entry: true,
        journal_comment: "Затраты на приёмку поставок на складе WB. Источник: delivery_amount (отчёт WB). Дт4401 / Кт7609.",
    },
    TurnoverClassDef {
        code: "adjustment_income",
        name: "Корректировка дохода",
        description: "Непривязанная корректировка, увеличивающая итоговый доход.",
        llm_description: "Прочее непривязанное начисление.",
        scope: TurnoverScope::Unlinked,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::FactOnly,
        sign_policy: SignPolicy::IncomePositive,
        report_group: ReportGroup::Adjustment,
        aliases: &["other_income"],
        source_examples: &["p903_wb_finance_report.additional_payment", "p903_wb_finance_report.cashback_amount"],
        formula_hint: "amount where layer=fact",
        notes: "Хранится положительной суммой. Счёт не определён в текущем плане.",
        debit_account: "",
        credit_account: "",
        generates_journal_entry: false,
        journal_comment: "Прочие начисления WB в пользу продавца (кэшбек, доплаты, прочие корректировки). Источник: additional_payment / cashback_amount. В журнале не отражается.",
    },
    TurnoverClassDef {
        code: "voluntary_return_compensation",
        name: "Добровольная компенсация при возврате",
        description: "Прочий доход продавца по операции добровольной компенсации при возврате.",
        llm_description: "Начисление WB в пользу продавца по добровольной компенсации при возврате.",
        scope: TurnoverScope::Unlinked,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::FactOnly,
        sign_policy: SignPolicy::IncomePositive,
        report_group: ReportGroup::Adjustment,
        aliases: &["voluntary_return_compensation"],
        source_examples: &["p903_wb_finance_report.ppvz_for_pay where supplier_oper_name = 'Добровольная компенсация при возврате'"],
        formula_hint: "amount where layer=fact and supplier_oper_name = 'Добровольная компенсация при возврате'",
        notes: "Используется только для отдельной WB-операции добровольной компенсации при возврате.",
        debit_account: "7609",
        credit_account: "91",
        generates_journal_entry: true,
        journal_comment: "Добровольная компенсация при возврате. Сумма = ppvz_for_pay. Дт7609 / Кт91.",
    },
    TurnoverClassDef {
        code: "adjustment_expense",
        name: "Корректировка расхода",
        description: "Непривязанная корректировка, уменьшающая итоговый результат.",
        llm_description: "Прочее непривязанное удержание или расход.",
        scope: TurnoverScope::Unlinked,
        value_kind: ValueKind::Money,
        agg_kind: AggKind::Sum,
        selection_rule: SelectionRule::FactOnly,
        sign_policy: SignPolicy::ExpensePositive,
        report_group: ReportGroup::Adjustment,
        aliases: &["other_expense"],
        source_examples: &["p903_wb_finance_report.additional_payment<0"],
        formula_hint: "amount where layer=fact",
        notes: "Хранится отрицательной суммой как расход. Счёт не определён в текущем плане.",
        debit_account: "",
        credit_account: "",
        generates_journal_entry: false,
        journal_comment: "Прочие удержания WB с продавца (переплаты, штрафные корректировки). Источник: additional_payment < 0. В журнале не отражается.",
    },
    TurnoverClassDef {
        code: "commission_percent",
        name: "Процент комиссии",
        description: "Справочный процент комиссии маркетплейса.",
        llm_description: "Процент комиссии для аналитики и LLM.",
        scope: TurnoverScope::Both,
        value_kind: ValueKind::Percent,
        agg_kind: AggKind::Avg,
        selection_rule: SelectionRule::PreferFact,
        sign_policy: SignPolicy::Natural,
        report_group: ReportGroup::Ratio,
        aliases: &["commission_rate"],
        source_examples: &["a012_wb_sales.line.commission_plan", "p903_wb_finance_report.commission_percent"],
        formula_hint: "prefer amount where layer=fact, else layer=oper",
        notes: "Справочное, не денежное значение.",
        debit_account: "",
        credit_account: "",
        generates_journal_entry: false,
        journal_comment: "Справочный процент комиссии WB (%). Не является денежным оборотом. В журнале не отражается.",
    },
];

pub fn get_turnover_class(code: &str) -> Option<&'static TurnoverClassDef> {
    TURNOVER_CLASSES.iter().find(|item| item.code == code)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn turnover_codes_are_unique() {
        let mut seen = HashSet::new();
        for item in TURNOVER_CLASSES {
            assert!(
                seen.insert(item.code),
                "duplicate turnover code: {}",
                item.code
            );
        }
    }

    #[test]
    fn all_turnovers_have_descriptions() {
        for item in TURNOVER_CLASSES {
            assert!(
                !item.name.trim().is_empty(),
                "missing name for {}",
                item.code
            );
            assert!(
                !item.description.trim().is_empty(),
                "missing description for {}",
                item.code
            );
            assert!(
                !item.llm_description.trim().is_empty(),
                "missing llm_description for {}",
                item.code
            );
            assert!(
                !item.journal_comment.trim().is_empty(),
                "missing journal_comment for {}",
                item.code
            );
        }
    }

    #[test]
    fn journal_entry_turnovers_have_accounts() {
        for item in TURNOVER_CLASSES {
            if item.generates_journal_entry {
                assert!(
                    !item.debit_account.is_empty(),
                    "turnover {} has generates_journal_entry=true but empty debit_account",
                    item.code
                );
                assert!(
                    !item.credit_account.is_empty(),
                    "turnover {} has generates_journal_entry=true but empty credit_account",
                    item.code
                );
            }
        }
    }
}
