//! Метаданные таблицы sys_general_ledger для LLM metadata registry.

use crate::shared::metadata::{
    EntityAiMetadata, EntityMetadataInfo, EntityType, EntityUiMetadata, FieldMetadata, FieldSource,
    FieldType, FieldUiMetadata, ValidationRules,
};

pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Projection,
    entity_name: "GeneralLedger",
    entity_index: "gl",
    collection_name: "general_ledger",
    table_name: Some("sys_general_ledger"),
    ui: EntityUiMetadata {
        element_name: "Запись журнала (GL)",
        element_name_en: Some("General Ledger Entry"),
        list_name: "Главная книга",
        list_name_en: Some("General Ledger"),
        icon: Some("database"),
    },
    ai: EntityAiMetadata {
        description: "Главная книга (sys_general_ledger): центральный учётный регистр. \
            Каждая строка — проводка Дт/Кт с кодом оборота (turnover_code). \
            Источники: p903_wb_finance_report, a012_wb_sales, a026_wb_advert_daily. \
            Слои: oper (оперативный), fact (финансовый отчёт).",
        questions: &[
            "Какова сумма выручки за период?",
            "Какие проводки сформированы по конкретному документу?",
            "Сколько записей в журнале по виду оборота X?",
            "Какие счета дебетуются/кредитуются при продаже?",
            "Каков оборот по счёту 44 за месяц?",
        ],
        related: &[
            "p903_wb_finance_report",
            "a012_wb_sales",
            "a026_wb_advert_daily",
            "a024_bi_indicator",
        ],
    },
    access: None,
};

pub const FIELDS: &[FieldMetadata] = &[
    FieldMetadata {
        name: "id",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Base,
        ui: FieldUiMetadata {
            label: "ID записи",
            label_en: Some("Entry ID"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: true,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules::required(),
        ai_hint: Some("UUID записи журнала"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "entry_date",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Дата проводки",
            label_en: Some("Entry Date"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("date"),
            column_width: Some(120),
        },
        validation: ValidationRules::required(),
        ai_hint: Some("Дата проводки в формате YYYY-MM-DD или ISO datetime"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "layer",
        rust_type: "String",
        field_type: FieldType::Enum,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Слой",
            label_en: Some("Layer"),
            placeholder: None,
            hint: Some("oper=оперативный, fact=финансовый отчёт"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(80),
        },
        validation: ValidationRules::required(),
        ai_hint: Some("Слой учёта: oper (заказы), fact (финансовый отчёт МП)"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: Some(&["oper", "fact", "plan"]),
    },
    FieldMetadata {
        name: "registrator_type",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Тип регистратора",
            label_en: Some("Registrator Type"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(160),
        },
        validation: ValidationRules::required(),
        ai_hint: Some(
            "Тип документа-источника: a012_wb_sales, p903_wb_finance_report, a026_wb_advert_daily",
        ),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "registrator_ref",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Регистратор (ссылка)",
            label_en: Some("Registrator Ref"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(200),
        },
        validation: ValidationRules::required(),
        ai_hint: Some("Чистый id регистратора; тип документа хранится отдельно в registrator_type"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "debit_account",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Счёт Дт",
            label_en: Some("Debit Account"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(80),
        },
        validation: ValidationRules::required(),
        ai_hint: Some(
            "Дебетуемый счёт по плану счетов (62, 44, 4401, 4402, 4403, 4404, 9001, 7609, ...)",
        ),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "credit_account",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Счёт Кт",
            label_en: Some("Credit Account"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(80),
        },
        validation: ValidationRules::required(),
        ai_hint: Some("Кредитуемый счёт по плану счетов (9001, 7609, 90, 76, ...)"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "amount",
        rust_type: "f64",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Сумма",
            label_en: Some("Amount"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: Some("money"),
            column_width: Some(120),
        },
        validation: ValidationRules::required(),
        ai_hint: Some("Сумма проводки. Знак может быть отрицательным в зависимости от оборота"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "turnover_code",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Вид оборота",
            label_en: Some("Turnover Code"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(160),
        },
        validation: ValidationRules::required(),
        ai_hint: Some(
            "Код вида оборота: customer_revenue, mp_commission, mp_logistics, \
             advertising_allocated, mp_penalty, mp_acquiring, ...",
        ),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "connection_mp_ref",
        rust_type: "Option<String>",
        field_type: FieldType::AggregateRef,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Подключение МП",
            label_en: Some("Marketplace Connection"),
            placeholder: None,
            hint: None,
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(180),
        },
        validation: ValidationRules::none(),
        ai_hint: Some("Ссылка на a006_connection_mp.id"),
        nested_fields: None,
        ref_aggregate: Some("a006"),
        enum_values: None,
    },
    FieldMetadata {
        name: "order_id",
        rust_type: "Option<String>",
        field_type: FieldType::Primitive,
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label: "Order ID",
            label_en: Some("Order ID"),
            placeholder: None,
            hint: Some("document_no/srid, если регистратор связан с заказом"),
            visible_in_list: true,
            visible_in_form: true,
            widget: None,
            column_width: Some(180),
        },
        validation: ValidationRules::none(),
        ai_hint: Some("Идентификатор заказа из регистратора: a012.document_no или p903.srid"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
    FieldMetadata {
        name: "created_at",
        rust_type: "String",
        field_type: FieldType::Primitive,
        source: FieldSource::Metadata,
        ui: FieldUiMetadata {
            label: "Создано",
            label_en: Some("Created At"),
            placeholder: None,
            hint: None,
            visible_in_list: false,
            visible_in_form: true,
            widget: Some("datetime"),
            column_width: None,
        },
        validation: ValidationRules::required(),
        ai_hint: Some("Время создания записи (ISO 8601)"),
        nested_fields: None,
        ref_aggregate: None,
        enum_values: None,
    },
];
