#![allow(dead_code)]

use crate::shared::metadata::{
    EntityAiMetadata, EntityMetadataInfo, EntityType, EntityUiMetadata, FieldMetadata, FieldSource,
    FieldType, FieldUiMetadata, ValidationRules,
};

pub const ENTITY_METADATA: EntityMetadataInfo = EntityMetadataInfo {
    schema_version: "1.0",
    entity_type: EntityType::Projection,
    entity_name: "MpOrderLineTurnover",
    entity_index: "p909",
    collection_name: "mp_order_line_turnovers",
    table_name: Some("p909_mp_order_line_turnovers"),
    ui: EntityUiMetadata {
        element_name: "MP Order Line Turnovers",
        element_name_en: Some("MP Order Line Turnovers"),
        list_name: "MP Order Line Turnovers",
        list_name_en: Some("MP Order Line Turnovers"),
        icon: Some("database"),
    },
    ai: EntityAiMetadata {
        description: "Универсальная проекция оборотов по строкам заказов маркетплейсов. Одна запись = один turnover_code по одной строке заказа, одному событию строки и одному layer.",
        questions: &[
            "Какие обороты по строкам заказов есть за период?",
            "Какой layer доступен по строке заказа: plan, oper или fact?",
            "Какой turnover_code дает выручку, комиссию, логистику или количество?",
            "Какие строки заказа связаны только с p903 без a015?",
        ],
        related: &[
            "a012_wb_sales",
            "a015_wb_orders",
            "p903_wb_finance_report",
            "p910_mp_unlinked_turnovers",
        ],
    },
    access: None,
};

pub const FIELDS: &[FieldMetadata] = &[
    field(
        "id",
        "String",
        "ID",
        true,
        true,
        Some("Стабильный business key строки проекции."),
        None,
        None,
    ),
    field(
        "connection_mp_ref",
        "String",
        "Connection",
        true,
        true,
        Some("UUID кабинета маркетплейса."),
        Some("a006_connection_mp"),
        None,
    ),
    field(
        "order_key",
        "String",
        "Order Key",
        true,
        true,
        Some("Бизнес-ключ заказа."),
        None,
        None,
    ),
    field(
        "line_key",
        "String",
        "Line Key",
        true,
        true,
        Some("Бизнес-ключ строки заказа."),
        None,
        None,
    ),
    field(
        "line_event_key",
        "String",
        "Line Event Key",
        false,
        true,
        Some("Стабильный ключ события строки для idempotent rebuild."),
        None,
        None,
    ),
    field(
        "event_kind",
        "String",
        "Event Kind",
        true,
        true,
        Some("Тип события строки: ordered, sold, returned, fee, adjustment, other."),
        None,
        Some(&["ordered", "sold", "returned", "fee", "adjustment", "other"]),
    ),
    field(
        "entry_date",
        "String",
        "Entry Date",
        true,
        true,
        Some("Бизнес-дата события."),
        None,
        None,
    ),
    field(
        "layer",
        "String",
        "Layer",
        true,
        true,
        Some("Слой оборота: plan, oper или fact."),
        None,
        Some(&["plan", "oper", "fact"]),
    ),
    field(
        "turnover_code",
        "String",
        "Turnover Code",
        true,
        true,
        Some("Код оборота из классификатора turnover classes."),
        None,
        None,
    ),
    field(
        "value_kind",
        "String",
        "Value Kind",
        true,
        true,
        Some("Тип значения оборота: money, quantity, percent, coefficient."),
        None,
        Some(&["money", "quantity", "percent", "coefficient"]),
    ),
    field(
        "agg_kind",
        "String",
        "Aggregation Kind",
        false,
        true,
        Some("Правило агрегации для BI: sum, avg, last, none."),
        None,
        Some(&["sum", "avg", "last", "none"]),
    ),
    field(
        "amount",
        "f64",
        "Amount",
        true,
        true,
        Some("Значение оборота в конкретном layer."),
        None,
        None,
    ),
    field(
        "nomenclature_ref",
        "Option<String>",
        "Nomenclature",
        false,
        false,
        Some("Ссылка на a004_nomenclature."),
        Some("a004_nomenclature"),
        None,
    ),
    field(
        "marketplace_product_ref",
        "Option<String>",
        "Marketplace Product",
        false,
        false,
        Some("Ссылка на a007_marketplace_product."),
        Some("a007_marketplace_product"),
        None,
    ),
    field(
        "registrator_type",
        "String",
        "Registrator Type",
        true,
        true,
        Some("Тип документа-источника: a015_wb_orders, a012_wb_sales, p903_wb_finance_report."),
        None,
        None,
    ),
    field(
        "registrator_ref",
        "String",
        "Registrator Ref",
        true,
        true,
        Some("Ссылка на конкретный документ-источник."),
        None,
        None,
    ),
    field(
        "link_status",
        "String",
        "Link Status",
        true,
        true,
        Some("Статус связности sibling-строк по layer."),
        None,
        Some(&["single", "oper_fact", "oper_plan", "fact_plan", "full"]),
    ),
    field(
        "created_at",
        "String",
        "Created At",
        false,
        false,
        Some("UTC timestamp создания строки проекции."),
        None,
        None,
    ),
    field(
        "updated_at",
        "String",
        "Updated At",
        false,
        false,
        Some("UTC timestamp последнего обновления строки проекции."),
        None,
        None,
    ),
];

const fn field(
    name: &'static str,
    rust_type: &'static str,
    label: &'static str,
    visible_in_list: bool,
    required: bool,
    ai_hint: Option<&'static str>,
    ref_aggregate: Option<&'static str>,
    enum_values: Option<&'static [&'static str]>,
) -> FieldMetadata {
    FieldMetadata {
        name,
        rust_type,
        field_type: if ref_aggregate.is_some() {
            FieldType::AggregateRef
        } else if enum_values.is_some() {
            FieldType::Enum
        } else {
            FieldType::Primitive
        },
        source: FieldSource::Specific,
        ui: FieldUiMetadata {
            label,
            label_en: None,
            placeholder: None,
            hint: None,
            visible_in_list,
            visible_in_form: false,
            widget: None,
            column_width: None,
        },
        validation: ValidationRules {
            required,
            min: None,
            max: None,
            min_length: None,
            max_length: None,
            pattern: None,
            custom_error: None,
        },
        ai_hint,
        nested_fields: None,
        ref_aggregate,
        enum_values,
    }
}
