#![allow(deprecated)]

use contracts::shared::universal_dashboard::{DataSourceSchema, FieldDef, FieldType};

/// DS02 Sales Register schema definition
pub static DS02_SCHEMA: DataSourceSchema = DataSourceSchema {
    id: "ds02_mp_sales_register",
    name: "Регистр продаж",
    fields: &[
        // Grouping fields - Dates
        FieldDef {
            id: "sale_date",
            name: "Дата продажи",
            field_type: FieldType::Date,
            can_group: true,
            can_aggregate: false,
            db_column: "sale_date",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        // Grouping fields - Basic attributes
        FieldDef {
            id: "marketplace",
            name: "Маркетплейс",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "marketplace",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "status_norm",
            name: "Статус",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "status_norm",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "seller_sku",
            name: "Артикул продавца",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "seller_sku",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "mp_item_id",
            name: "ID товара на МП",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "mp_item_id",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "currency_code",
            name: "Валюта",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "currency_code",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        // Reference fields with display names
        FieldDef {
            id: "connection_mp_ref",
            name: "Подключение",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "connection_mp_ref",
            ref_table: Some("a006_connection_mp"),
            ref_display_column: Some("description"),
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "organization_ref",
            name: "Организация",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "organization_ref",
            ref_table: Some("a002_organization"),
            ref_display_column: Some("description"),
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "marketplace_product_ref",
            name: "Товар МП",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "marketplace_product_ref",
            ref_table: Some("a007_marketplace_product"),
            ref_display_column: Some("description"),
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "nomenclature_ref",
            name: "Номенклатура",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "nomenclature_ref",
            ref_table: Some("a004_nomenclature"),
            ref_display_column: Some("description"),
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "registrator_ref",
            name: "Регистратор",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "registrator_ref",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        // Nomenclature dimensions (from joined a004_nomenclature table)
        FieldDef {
            id: "dim1_category",
            name: "Категория",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "dim1_category",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        FieldDef {
            id: "dim2_line",
            name: "Линейка",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "dim2_line",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        FieldDef {
            id: "dim3_model",
            name: "Модель",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "dim3_model",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        FieldDef {
            id: "dim4_format",
            name: "Формат",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "dim4_format",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        FieldDef {
            id: "dim5_sink",
            name: "Раковина",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "dim5_sink",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        FieldDef {
            id: "dim6_size",
            name: "Размер",
            field_type: FieldType::Text,
            can_group: true,
            can_aggregate: false,
            db_column: "dim6_size",
            ref_table: None,
            ref_display_column: None,
            source_table: Some("a004_nomenclature"),
            join_on_column: Some("nomenclature_ref"),
        },
        // Numeric fields (can aggregate)
        FieldDef {
            id: "qty",
            name: "Количество",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "qty",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "price_list",
            name: "Цена по прайсу",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "price_list",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "discount_total",
            name: "Общая скидка",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "discount_total",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "price_effective",
            name: "Эффективная цена",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "price_effective",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "amount_line",
            name: "Сумма по строке",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "amount_line",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
        FieldDef {
            id: "cost",
            name: "Себестоимость",
            field_type: FieldType::Numeric,
            can_group: false,
            can_aggregate: true,
            db_column: "cost",
            ref_table: None,
            ref_display_column: None,
            source_table: None,
            join_on_column: None,
        },
    ],
};

/// Table name for this schema
pub const DS02_TABLE_NAME: &str = "p900_sales_register";
